import Head from "next/head";
import styles from "../styles/Home.module.css";

import UserList from "../components/user-list";

type Users = {
  user: User[];
};

type User = {
  id: string;
  name: string;
  email: string;
  statusId: string;
};

export async function getServerSideProps() {
  const response = await fetch("http://localhost:3001/user", {
    method: "GET",
  });

  const json = await response.json();

  const props = json;

  return { props };
}

const Home = (props: Users) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Praha Challenge!</a>
        </h1>

        <UserList users={props.user} />
      </main>
    </div>
  );
};

export default Home;
