import Head from "next/head";
import styles from "../styles/Home.module.css";

type Users = {
  user: User[];
};

type User = {
  id: string;
  name: string;
  email: string;
  statusId: string;
};

export async function getServerSideProps() {
  const response = await fetch("http://localhost:3001/user", {
    method: "GET",
  });

  const json = await response.json();

  const props = json;

  return { props };
}

const Home = (props: Users) => {
  console.log(props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Praha Challenge!</a>
        </h1>

        <h2>Member List</h2>
        <div className={styles.grid}>
          {props.user.map((user) => (
            <a key={user.id} href="#" className={styles.card}>
              <h2>{user.name}</h2>
              <p>{user.email}</p>
              <p>{`Status: ${user.statusId}`}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
